myBlog/urls.py
# -*- coding: UTF-8 -*-
"""myBlog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/dev/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import urls as auth_urls
from django.conf.urls.static import static
from django.conf import settings
from personal import urls as self_urls
from wechat import urls as wechat_urls
from blogapi import urls as blog_api_urls
from blog import views
from blog import feeds

'''
python manage.py createsuperuser
'''

'''
app_name='blog' 告诉 Django 这个 urls.py 模块是属于 blog 应用的
防止 index、detail等与别的视图函数冲突
'''
#app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    # (?P<pk>[0-9]+)表示命名捕获组，正则匹配的数字会在调用视图函数 detail 时被传递进去
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # 该分类页由首页跳转，name指定为【kind】，方便在模板中通过url标签找到，但http地址还是【catergory】
    url(r'^category/$', views.kind, name='kind'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/$', views.tag, name='tag'),
    url(r'^about/$', views.about, name='about'),
    url(r'^comment/blog/(?P<blog_pk>[0-9]+)/$', views.blog_comment, name='blog_comment'),
    url(r'^all/rss/$', feeds.AllBlogsRssFeed(), name='rss'),
    # 将 auth 应用中的 urls 模块包含进来,默认的登录视图函数渲染的是 registration/login.html 模板
    url(r'^users/', include(auth_urls)),
    url(r'^users/', include(self_urls, namespace='users')),
    url(r'^wechat/', include(wechat_urls, namespace='wechat')),
    url(r'^api/', include(blog_api_urls, namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
# -*- coding: UTF-8 -*-
'''
Created on 2018年1月10日

@author: zhguixin
'''

from django.conf.urls import url
from personal import views

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^register/$', views.register, name='register'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

blog/models.py
# -*- coding: UTF-8 -*-
from django.db import models
#from django.urls.base import reverse # Django 1.10版本
from django.core.urlresolvers import reverse # Django 1.9 的版本

'''
各个数据表的关系： 
博客：一篇博客可以有多个标签，多个评论，属于一个分类 
标签：一类标签可以赋予多篇博客，一个博客也可以由多个标签，所以是博客和标签是多对多的关系 
分类：一个分类内部可以有多个博客，我们规定一个博客只对应一个分类，所以博客和分类是一对多的关系 
评论：很明显一个评论属于一个博客，而一个博客可以有很多的评论，所以是博客和评论是一对多的关系。
'''
# Create your models here.
# 注意：这里表的字段名取为【Catagory】,视图函数，模板使用的url则为【Category】
# （感觉自己把自己坑了，两个名字没有去一样）
class Catagory(models.Model):
    """
    博客分类
    """
    name = models.CharField(u'名称',max_length=30)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'pk':self.pk})

class Tag(models.Model):
    """
    博客标签
    """
    name = models.CharField(u'名称',max_length=16)

    def __unicode__(self):
        return self.name

class Blog(models.Model):
    """
    博客，允许作者为空，摘要为空
    """
    title = models.CharField(u'标题',max_length=32)
    author = models.CharField(u'作者',max_length=16, blank=True)
    abstract = models.CharField(u'摘要',max_length=200, blank=True)
    content = models.TextField(u'博客正文')
    created = models.DateTimeField(u'发布时间',auto_now_add=True)
    catagory = models.ForeignKey(Catagory,verbose_name=u'分类', default= '')
    tags = models.ManyToManyField(Tag,verbose_name=u'标签', default='')

    class Meta:
        ordering = ['-created', 'title']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        # pk 和 id 是等价的,对应数据库中的id值
        # 第一个参数 blog:detail 的意义表示 blog 应用下的 name=detail 的函数
        return reverse('detail', kwargs={'pk':self.pk})

class Comment(models.Model):
    """
    评论
    """
    blog = models.ForeignKey(Blog,verbose_name=u'博客')
    name = models.CharField(u'称呼',max_length=16)
    email = models.EmailField(u'邮箱')
    content = models.CharField(u'内容',max_length=240)
    created = models.DateTimeField(u'发布时间',auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return self.name

templates/about.html
{% extends "base.html" %}

{% block title %}关于{% endblock title %}
{% block mainbody %}
<div class="container">
    <br>
    {{ info|safe}}
    
    <div class="rss">
      <a href="{% url 'rss' %}"><span class="octicon octicon-rss"></span> RSS 订阅</a>
    </div>
    <div class="rss">
      <a href="{% url 'users:gallery' %}" onclick="window.open(this.href);return false;">
        <span class="octicon octicon-sign-in"></span>了解更多</a>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{% block title %}zhguixin{% endblock title %}</title>
<link rel="shortcut icon" href="/static/img/favicon.ico">
<link rel="stylesheet" type="text/css" href="/static/css/style.css" >
<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.bootcss.com/octicons/3.5.0/octicons.min.css" >
<link  rel="stylesheet" href="http://cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css">
{% block css %}
{% endblock css %}
<script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="http://cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
<script type="text/javascript" src="/static/js/page.js"></script>
{% block js %}
{% endblock js %}
<style>
body {
    /*padding-top: 40px; 不固定顶部导航栏不需要此属性*/
    font-family: 'Lora', 'Times New Roman', serif;
    color: #404040;
    font-size: 20px;
}
.rectangle{
    border-radius: 0px;
}

/**
  分页相关
*/
.pagination {
    margin-left: 50%;
    margin-top: 25px;
    text-align: center;
}
.pagination a {
  display: inline-block;
  line-height: 38px;
  padding: 0 15px;
  margin-right: 4px;
  text-align: center;
  background-color: #fff;
  user-select: none;
  cursor: pointer;
  font-size: 14px;
  border: 1px solid #d7dde4;
  border-radius: 4px;
  transition: all .2s ease-in-out;
}
.pagination a:hover {
  color: #A161BF;
  border: 1px solid #A161BF;
}
.pagination .current-page {color: white; background-color: #A161BF;}
.pagination .current-page:hover {
  color: white;
  border: 1px solid #A161BF;
}
.pagination span {
  display: inline-block;
  font-size: 20px;
  line-height: 38px;
  padding: 0 8px;
  margin-right: 4px;
}

</style>
<script>
$(document).ready(function () {
    if ($('#back-to-top').length) {
        var scrollTrigger = 200,
            backToTop = function () {
                var scrollTop = $(window).scrollTop();
                if (scrollTop > scrollTrigger) {
                    $('#back-to-top').addClass('show');
                } else {
                    $('#back-to-top').removeClass('show');
                }
            };
        backToTop();
        $(window).on('scroll', function () {
            backToTop();
        });
        $('#back-to-top').on('click', function (e) {
            e.preventDefault();
            $('html,body').animate({
                scrollTop: 0
            }, 700);
        });
    }
});
</script>
</head>
<body> <!-- navbar-fixed-top  固定顶部导航栏会导致锚点偏移 -->
    <nav class="navbar navbar-inverse rectangle" role="navigation">
        <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="javascript:void(0)">书山有路勤为径，学海无涯苦作舟</a>
        </div>
        {# <!-- 通过 Django template的slice过滤掉request.path中的URL相对路径,只保留前num位 --> #}
        {# {{ request.path|slice:"num" }} #}
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li {% if request.path == "/" %} class="active" {% endif %}>
                    <a href="/"><span class="octicon octicon-home"></span>&nbsp;&nbsp;首页</a></li>
                <li {% if request.path|slice:"4" == "/cat" %} class="active" {% endif %}>
                    <a href="{% url 'kind' %}"><span class="octicon octicon-list-unordered"></span>&nbsp;&nbsp;分类</a></li>
                <li {% if request.path|slice:"4" == "/tag" %} class="active" {% endif %}>
                    <a href="{% url 'tag' %}"><span class="octicon octicon-tag"></span>&nbsp;&nbsp;标签</a></li>
                <li {% if request.path|slice:"4" == "/abo" %} class="active" {% endif %}>
                    <a href="{% url 'about' %}"><span class="octicon octicon-info"></span>&nbsp;&nbsp;关于</a></li>
            </ul>
        </div>
        </div>
    </nav>

    {% block mainbody %}
       <p>模板信息</p>
    {% endblock %}

<a href="#" id="back-to-top" title="Back to top">
    <i class="glyphicon glyphicon-chevron-up"></i>
</a>

<div id="footer" class="footer">
    <div class="container">
        <br>
        <p>
            Copyright © 2018 <a href="#" style="color: white; text-decoration: none;" data-toggle="modal"
                                data-target="#profile-modal">GuiXin's Blog</a> 联系我: zhguixin@163.com
        </p>
    </div>
</div>

</body>
</html>

templates/category.html
{% extends "base.html" %}

{% block title %}分类{% endblock title %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/article_list.css" />
{% endblock css %}

{% block mainbody %}
{% load get_category %}

<div class="container">
  <div class="main">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <span class="octicon octicon-list-unordered"></span>&nbsp;Categories
            <span class="caret"></span>
        </button>
        {% get_category as category_list %}
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            {% for category in category_list %}
            <li>
              <a  class="categories-item" href="{% url 'category' category.pk %}">{{ category.name }}
                <span class="categories-badge">({{ category.num_blogs }})</span></a>
            </li>
            {% empty %}
              暂无归档
            {% endfor %}
        </ul>
    </div> <!-- end dropdown -->

    {% for blog in blogs %}
        <article>
            <span class="octicon octicon-calendar"></span> &nbsp;&nbsp;{{ blog.created|date:"Y-m-d" }}
            <div class="module">
                <a class="title" href="{{blog.get_absolute_url}}"> {{ blog.title }}</a>
                <footer class="blog-footer">
                    <span class="octicon octicon-file-submodule"></span>&nbsp;&nbsp;<b>Archive:</b>&nbsp;&nbsp;
                      <a href="/category/">{{ blog.catagory.name }}</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;<span class="octicon octicon-tag"></span>&nbsp;&nbsp;<b>Tags:</b>
                    {% for tag in blog.tags.all %}
                      &nbsp;<a href="/tag/#{{tag.name}}">{{ tag.name }}</a>
                    {% endfor %}
                     &nbsp;&nbsp;&nbsp;&nbsp;<span class="octicon octicon-comment"></span>&nbsp;&nbsp;<b>Comments:</b>
                     &nbsp;&nbsp;<a href="{{blog.get_absolute_url}}#comment-area">{{ blog.comment_set.count }}</a>
                </footer>
            </div>
        </article>
    {% endfor %}
    
    </div> <!-- end container -->
</div> <!-- end main -->

{% endblock %}

templates/comment.html
<section class="comment-area" id="comment-area">
  <h3>发表评论</h3>
  <form action="{% url 'blog_comment' blog.pk %}" method="post" class="comment-form">
  {% csrf_token %}
   <div class="row">
    <div class="col-md-6">
      <label for="{{ form.name.id_for_label }}">昵称：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-6">
      <label for="{{ form.email.id_for_label }}">邮箱：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.content.id_for_label }}">评论：</label>
      {{ form.content }}
      {{ form.content.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
   </div> <!-- end row -->
  </form>

<ul class="comment-list list-unstyled">
  <h3>评论列表，共 <span>{{comment_list|length}}</span> 条评论</h3>
  {% for comment in comment_list %}
  <li class="comment-item">
    <span class="nickname">{{ comment.name }}</span>
    <time class="submit-date">{{ comment.created |date:"Y-m-d H:i:s"}}</time>
    <div class="text">
      {{ comment.content }}
    </div>
  </li>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>
</section>

templates/comment2.html
<section id="comment-area">
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-push-1">
        <hr class="boundary">
            <h3 style="color: #5694ca;"><b>评论区</b></h3>
            <ul class="comment-list list-unstyled">
              {% for comment in comment_list %}
              <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.created |date:"Y-m-d H:i:s"}}</time>
                <div class="text">
                  {{ comment.content }}
                </div>
              </li>
              {% empty %}暂无评论
              {% endfor %}
            </ul>
            <iframe id="id_iframe" name="id_iframe" style="display:none;"></iframe>
            <div class="add-comment" id="vNewComment">
                <h3 style="color: #5694ca;"><b>留下你的评论呗</b></h3>
                <form class="form-horizontal" action="{% url 'blog_comment' blog.pk %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-4">
                            <label for="{{ form.name.id_for_label }}" class="control-label">Name <span class="text-theme">*</span></label>
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                            <label for="{{ form.email.id_for_label }}" class="control-label">Email <span class="text-theme">*</span>（仅用于回复通知）</label>
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                            <label class="control-label">Website</label>
                            <input type="url" class="form-control" id="website">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="{{ form.content.id_for_label }}" class="control-label">Comment <span class="text-theme">*</span></label>
                            {{ form.content }}
                            {{ form.content.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-theme">Post Comment</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</section>
<script>
$(document).ready(function () {
    var displaytoc = function() {
        var top = document.getElementById('comment-area').getBoundingClientRect().top;
        // console.log(top);
        if(top < 200) {
            $('#toc').hide();
        } else {
            $('#toc').show();
        }
    }
    displaytoc();
    $(window).on('scroll', function () {
        displaytoc();
    });

    $('#{{ form.name.id_for_label }}').attr('class','form-control').attr('required','');
    $('#{{ form.email.id_for_label }}').attr('class','form-control').attr('required','');
    $('#{{ form.content.id_for_label }}').attr('class','form-control').attr('required','');

    var result = {{ result|safe }};
    if (result == 'failed') {
        location.hash='vNewComment';
    }
});
</script>

templates/detail.html
{% extends "base.html" %}

{% block title %} {{ blog.title }}{% endblock title %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/article_list.css" />
<link rel="stylesheet" type="text/css" href="/static/css/comment2.css" />
<link rel="stylesheet" type="text/css" href="/static/css/vs.css" >
<link rel="dns-prefetch" href="//cdn.mathjax.org" />
{% endblock css %}

{% block js %}
<script src="http://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    showProcessingMessages: false, //关闭js加载过程信息
    messageStyle: "none", //不显示信息
    extensions: ["tex2jax.js"],
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
        inlineMath:  [ ["$", "$"] ], //行内公式选择$
        displayMath: [ ["$$","$$"] ], //段内公式选择$$
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code','a'], //避开某些标签
        ignoreClass:"comment-content" //避开含该Class的标签
    },
    "HTML-CSS": {
        availableFonts: ["STIX","TeX"], //可选字体
        showMathMenu: false //关闭右击菜单显示
    }
});
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
</script>
{% endblock js %}


{% block mainbody %}
    <div class="container">
    <div class="row">
    <div class="col-sm-9">
        <p class="pull-right visible-xs">
            <button class="btn-xs btn btn-default" type="button">
            <span class="octicon octicon-list-unordered"></span>&nbsp;目录已隐藏
            <span class="caret"></span>
           </button>
        </p>
        <header>
            <div class="module">
                <h2 class="article-title"> {{ blog.title }} </h2>
            </div>
            <p class="meta"> Posted on {{ blog.created|date:"Y-m-d" }}</p>
            <span class="octicon octicon-file-submodule"></span>
              <a href="{% url 'category' blog.catagory.pk %}">{{blog.catagory.name}}</a>
            {% for tag in blog.tags.all %}
              &nbsp;&nbsp;<span class="octicon octicon-tag"></span>
              <a href="/tag/#{{tag.name}}">{{ tag.name }}</a>
            {% endfor %}
        </header>
        <hr class="boundary">
        <p> {{blog.abstract}}</p><br>
        <p> {{blog.content|safe}}</p>
        <hr>
        {% include 'share.html' %}
        <br>
    </div> <!-- end col -->
    <div id="toc" class="col-sm-3">{{blog.toc|safe}}</div>
    </div> <!-- end row -->
    </div><!-- end container -->
    {% include 'comment2.html' %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/article_list.css" />
    {% endblock css %}

{% block mainbody %}

    {% load paginate_tags %}
    {% paginate blogs 5 %}

    {% for blog in blogs %}
    <div class="container">
    <div class="main">
        <article>
            <p class="meta">
                <span class="octicon octicon-clock"></span> Posted on {{ blog.created|date:"Y-m-d" }}
            </p>
            <div class="module">
                <a class="title" href="{{blog.get_absolute_url}}"> {{ blog.title }}</a>
                <p>{{ blog.abstract }}</p>
                <footer class="blog-footer">
                    <span class="octicon octicon-person"></span>&nbsp;&nbsp;<b>Author:</b>&nbsp;&nbsp;
                        <a href="/about/">{{ blog.author }}</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;<span class="octicon octicon-tag"></span>&nbsp;&nbsp;<b>Tags:</b>
                    {% for tag in blog.tags.all %}
                    &nbsp;<a href="/tag/#{{tag.name}}">{{ tag.name }}</a>
                    {% endfor %}
                </footer>
            </div>
        </article>
    </div>
    </div>
    {% endfor %}

    {% include 'pagination.html' %}

{% endblock %}

templates/pagination.html
<div class="pagination">
    {% if blogs.has_previous %}
        <a class="previous-page" href="?page={{ blogs.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current-page">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current-page">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current-page">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if blogs.has_next %}
        <a class="next-page" href="?page={{ blogs.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>

templates/share.html
<div class="bdsharebuttonbox">
    <a href="#" class="bds_more" data-cmd="more">分享到：</a><a href="#"
        class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a><a
        href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a
        href="#" class="bds_evernotecn" data-cmd="evernotecn"
        title="分享到印象笔记">印象笔记</a><a href="#" class="bds_youdao"
        data-cmd="youdao" title="分享到有道云笔记">有道云笔记</a>
</div>
<script>
window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"1","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{"bdSize":16}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>

templates/tag.html
{% extends "base.html" %}

{% block title %}标签{% endblock title %}

{% block js %}
<script type="text/javascript" src="/static/js/tag.js"></script>
{% endblock js %}

{% block mainbody %}
{% load get_tags %}
<div class="container">
      {% get_tags as tag_list %}

      <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="collapse-btn">
             <button id="openAll" type="button" class="btn pull-right btn-warning btn-default">全部展开</button>
             <button id="closeAll" type="button" class="btn pull-right btn-default btn-info">全部收缩</button>
           </div>
        </div>
      </div>
      <hr>

    <div class="row clearfix">
    {% for tag in tag_list %}
        <div class="col-md-6 column">
            <!-- collapse panel -->
            <div class="panel panel-default"> <!-- panel-default -->
                <div class="panel-heading">
                     <h3 id="{{tag.name}}" class="panel-title"><a data-toggle="collapse" style="color:#0099ff"
                     href="#{{tag.pk}}">{{ tag.name }}</a>&nbsp;<span>({{ tag.num_blogs }})</span></h3>
                </div>
                <div id="{{tag.pk}}" class="panel-collapse in">
                    <div class="panel-body">
                        {% get_blogs_by_tag tag.pk as blogs%}
                        <ul>
                          {% for blog in blogs %}
                            <li>
                              <span>{{ blog.created|date:"Y-m-d" }}</span>&nbsp;>>&nbsp;
                              <a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
                            </li>
                          {% endfor %}
                        </ul>
                    </div>
                </div>
            </div> <!-- end panel -->
        </div> <!-- end column -->
    {% endfor %}
    </div> <!-- end row -->
</div> <!-- end container -->

{% endblock %}