myBlog/urls.py
# -*- coding: UTF-8 -*-
"""myBlog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/dev/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import urls as auth_urls
from django.conf.urls.static import static
from django.conf import settings
from personal import urls as self_urls
from wechat import urls as wechat_urls
from blogapi import urls as blog_api_urls
from blog import views
from blog import feeds

'''
python manage.py createsuperuser
'''

'''
app_name='blog' 告诉 Django 这个 urls.py 模块是属于 blog 应用的
防止 index、detail等与别的视图函数冲突
'''
#app_name='blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    # (?P<pk>[0-9]+)表示命名捕获组，正则匹配的数字会在调用视图函数 detail 时被传递进去
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # 该分类页由首页跳转，name指定为【kind】，方便在模板中通过url标签找到，但http地址还是【catergory】
    url(r'^category/$', views.kind, name='kind'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/$', views.tag, name='tag'),
    url(r'^about/$', views.about, name='about'),
    url(r'^comment/blog/(?P<blog_pk>[0-9]+)/$', views.blog_comment, name='blog_comment'),
    url(r'^all/rss/$', feeds.AllBlogsRssFeed(), name='rss'),
    # 将 auth 应用中的 urls 模块包含进来,默认的登录视图函数渲染的是 registration/login.html 模板
    url(r'^users/', include(auth_urls)),
    url(r'^users/', include(self_urls, namespace='users')),
    url(r'^wechat/', include(wechat_urls, namespace='wechat')),
    url(r'^api/', include(blog_api_urls, namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
# -*- coding: UTF-8 -*-
'''
Created on 2018年1月10日

@author: zhguixin
'''

from django.conf.urls import url
from personal import views

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^register/$', views.register, name='register'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

templates/users/gallery.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Gallery</title>
    <link rel="shortcut icon" href="/static/img/gallery_favicon.ico">
    <link rel="stylesheet" type="text/css" href="/static/css/gallery_main.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/lightbox2/2.10.0/css/lightbox.min.css" >
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <link  rel="stylesheet" href="http://cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css">
    <script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js"></script>
    <script src="https://cdn.bootcss.com/lightbox2/2.10.0/js/lightbox.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery.transit/0.9.12/jquery.transit.min.js"></script>
    <script type="text/javascript" src="/static/js/gallery_main.js"></script>
</head>

<style>
/**
  返回顶部
*/
#back-to-top
{
    position:        fixed;
    bottom:          40px;
    right:           40px;
    z-index:         9999;
    width:           32px;
    height:          32px;
    text-align:      center;
    font-size:       24px;
    line-height:     30px;
    cursor:          pointer;
    border:          0;
    border-radius:   2px;
    text-decoration: none;
    transition:      opacity 0.2s ease-out;
    opacity:         0;
    transition:      all .3s;
}
#back-to-top.show
{
    opacity: 1;
}
</style>
<body>

<div class="flex-center">
    <div class="container">
            <h1 class="logo text-primary text-center">摄影相册</h1>
            {% if user.is_authenticated %}
            <div id="content"><div id="snowflake">
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <div style="text-align:right">
                <button class="btn btn-default">
                  <a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                </button>
                <button class="btn btn-default">
                  <a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                </button>
                </div>
                {% include 'users/show.html' %}
            </div></div>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a></button>
                </p>
                <p class="text-danger text-center"><span class="count">5</span>秒后关闭当前页面…</p>
            {% endif %}
            <a href="#" id="back-to-top" title="Back to top">
                <img src="/static/img/to_top.png"></img>
            </a>
    </div>
</div>

<script>
$(document).ready(function () {
    if ($('#back-to-top').length) {
        var scrollTrigger = 200,
            backToTop = function () {
                var scrollTop = $(window).scrollTop();
                if (scrollTop > scrollTrigger) {
                    $('#back-to-top').addClass('show');
                } else {
                    $('#back-to-top').removeClass('show');
                }
            };
        backToTop();
        $(window).on('scroll', function () {
            backToTop();
        });
        $('#back-to-top').on('click', function (e) {
            e.preventDefault();
            $('html,body').animate({
                scrollTop: 0
            }, 700);
        });
    }
});
</script>

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="shortcut icon" href="/static/img/gallery_favicon.ico">
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3 class="text-primary">注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/users/show.html
<p> <b>在我看来，某个东西你不把它拍下来就不能说你见过。——艾米丽·佐拉 </b></p>

{% load thumbnail %}
{% load get_gallery_category %}

<h3>风景照<span>(5)</span></h3>
<div>
  <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-3.jpg" data-lightbox="example-set" data-title="Click the right half of the image to move forward.">
    <img class="gallery-image" data-original="http://lokeshdhakar.com/projects/lightbox2/images/thumb-3.jpg" alt=""/></a>
  <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-4.jpg" data-lightbox="example-set" data-title="Or press the right arrow on your keyboard.">
    <img class="gallery-image" data-original="http://lokeshdhakar.com/projects/lightbox2/images/thumb-4.jpg" alt="" /></a>
  <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-5.jpg" data-lightbox="example-set" data-title="The next image in the set is preloaded as you're viewing.">
    <img class="gallery-image" data-original="http://lokeshdhakar.com/projects/lightbox2/images/thumb-5.jpg" alt="" /></a>
  <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-6.jpg" data-lightbox="example-set" data-title="Click anywhere outside the image or the X to the right to close.">
    <img class="gallery-image" data-original="http://lokeshdhakar.com/projects/lightbox2/images/thumb-6.jpg" alt="" /></a>
  <a href="/static/img/blog_img.jpg" data-lightbox="example-set" data-title="安静的阅读">
    <img class="gallery-image" data-original="/static/img/blog_img.jpg" alt="" /></a>
</div>

{% for category in cates %}
{% get_images_by_category category.pk as images %}
<hr>
<h3>{{ category.name }} <span>({{images | length}})</span> </h3>
  <div>
    {% for img in images %}
      <a href="{{ img.original.url }}" data-lightbox="{{ category.name }}" data-title="{{img.description}}">
        <img class="gallery-image" data-original="{{ img.original.thumbnail.url }}" alt="" /></a>
    {% endfor %}
  </div>
{% endfor %}

<script>
    lightbox.option({
      // 'resizeDuration': 200,
      // 'wrapAround': true,
      'albumLabel': "第 %1 张/共 %2 张"
    })
    $(function() {
        $("img.gallery-image").lazyload({
            effect : "fadeIn"
        });
    });
</script>